// ── business-email.html bundle ────────────────────
import '../../assets/js/translations.js'
import '../../assets/js/translations/header-footer/header.js'
import '../../assets/js/translations/Package/hero.js'
import '../../assets/js/translations/business-email/pricing.js'
import '../../assets/js/translations/Package/features.js'
import '../../assets/js/translations/Package/comparison.js'
import '../../assets/js/translations/Package/testimonial.js'
import '../../assets/js/translations/Package/faq.js'
import '../../assets/js/translations/Package/wordpress.js'
import '../../assets/js/translations/Package/support.js'
import '../../assets/js/translations/header-footer/footer.js'
import '../../assets/js/i18n.js'
import '../../assets/js/header.js'
import '../../assets/js/utils.js'
import '../../assets/js/billing.js'
import '../../assets/js/animations.js'
import '../../assets/js/main.js'
