// ── index.html bundle ──────────────────────────────
import '../../assets/js/translations.js'
import '../../assets/js/translations/header-footer/header.js'
import '../../assets/js/translations/Home/hero.js'
import '../../assets/js/translations/Home/pricing.js'
import '../../assets/js/translations/Home/domain.js'
import '../../assets/js/translations/Home/services.js'
import '../../assets/js/translations/Home/wordpress.js'
import '../../assets/js/translations/Home/support.js'
import '../../assets/js/translations/header-footer/footer.js'
import '../../assets/js/i18n.js'
import '../../assets/js/header.js'
import '../../assets/js/utils.js'
import '../../assets/js/pricing.js'
import '../../assets/js/billing.js'
import '../../assets/js/animations.js'
import '../../assets/js/main.js'
